RTEcompile:
	python GradientDescent_test.py > results.txt

RTEstartView:
	uzbl-browser results.txt --named RTE &

RTEview:
	echo reload > /tmp/uzbl_fifo_RTE

RTEstopView:
	echo exit > /tmp/uzbl_fifo_RTE


